### ISSUE TITLE
How to check validity before form submit

### ISSUE THREAD

**Issue by ga5tan** [carreath/jquery.password-validation#1]
Hi

@carreath 
how can I check if passwords are ok, before I submit my form?

**Comment by carreath** [comment]
When you call the passwordValudation function you hand it the is of the confirm field. as well as a callback function that gives you the state of the validation. 
This function will be called each keystroke so you should have the current state each time you press a key.
Reference my short demo for a sample usage.

**Comment by ga5tan** [comment]
oh, ok. in callback I am setting global variable, which I check when submitting. thx man
